#Author: shweta.sonar@extentia.com
Feature: MultiMedia feature

  @MultiMedia @SmokeTest
  Scenario Outline: To verify Multimedia activity using softlogin
    Given I navigate to Multimedia Activity page "<MultiMediaSofturl>"
    When I click on the Begin Activity button
    And I watch all video
    And I click on the Continue to Post Test button
    And I select all the answers for posttest question
    And I click on the Continue to Evaluation button
    And I click on Continue to Evaluation button on popup
    Then I am able to see the password banner page "<ExpectedLoginTitle>" and enterdetails "<EmailAddress>" "<Password>"
    And I click on the Save & Continue to Evaluation button on evaluation popup
    And I select all answer for the evaluation questions
    And I click on the Submit Evaluation button
    And The activity is completed and certificate should be generated

    #And I logout from the application
    #Examples: 
      #| MultiMediaSofturl                                                                                                                                                                                                                        | PostTQ_Ans1                                                                                                                 | PostTQ_Ans2                                                              | PostTQ_Ans3                                                               | ExpectedLoginTitle | EmailAddress             | Password    | EvQAns_1 | EvQAns2 | EvQAns_3_01    | EvQAns_3_02    | EvQAns_3_03    | EvQAns_4_01    | EvQAns_4_02    | EvQAns_4_03    | EvQAns_4_04    | EvQAns_4_05    | EvQAns_4_06    | EvQAns_4_07    | EvQAns_5 | EvQAns_6 | EvQAns_7 | EvQAns_8                                                                         | EvQAns_9 | EvQAns_10      | EvQAns_11 | EvQAns_12 | EvQAns_13 | EvQAns_14 | EvQAns_15  | EvQAns_16                         | EvQAns_17 | EvQAns_18 | EvQAns_19 | EvQAns_20 |
      #| https://uat.practicingclinicians.com/CE-CME/cardiovascular-disease/automationsanity-copy-647-the-biggest-risk-to-cardiovascular-health-addressing-social-determinants-of-health-in-nvaf/24239?token=A380C494-0E93-41BE-B60D-7C50641C50BF | Black race is associated with higher rates of atrial fibrillation–related cardiovascular disease compared with White race | Implement telehealth services for anticoagulant education and monitoring | Lower rates of DOACs in Black individuals compared with White individuals | Password Required  | testra+70@mailinator.com | Shivani@123 |        0 | Never   | Strongly Agree | Strongly Agree | Strongly Agree | Strongly Agree | Strongly Agree | Strongly Agree | Strongly Agree | Strongly Agree | Strongly Agree | Strongly Agree |      123 | Yes      | NA       | I do plan to implement changes in my practice based on the information presented | test     | Very committed |       456 | Yes       | test      | Yes       | Competence | Lack of evidence-based guidelines | test      | test      | test      |       .50 |
    Examples: 
      | MultiMediaSofturl                                                                                                                                                                                                        | PostTQ_Ans1                                                                                                                 | PostTQ_Ans2                                                              | PostTQ_Ans3                                                               | ExpectedLoginTitle | EmailAddress             | Password    | EvQAns_1 | EvQAns2 | EvQAns_3_01    | EvQAns_3_02    | EvQAns_3_03    | EvQAns_4_01    | EvQAns_4_02    | EvQAns_4_03    | EvQAns_4_04    | EvQAns_4_05    | EvQAns_4_06    | EvQAns_4_07    | EvQAns_5 | EvQAns_6 | EvQAns_7 | EvQAns_8                                                                         | EvQAns_9 | EvQAns_10      | EvQAns_11 | EvQAns_12 | EvQAns_13 | EvQAns_14 | EvQAns_15  | EvQAns_16                         | EvQAns_17 | EvQAns_18 | EvQAns_19 | EvQAns_20 |
      | https://practicingclinicians.com/CE-CME/cardiovascular-disease/Copy_97_the-biggest-risk-to-cardiovascular-health-addressing-social-determinants-of-health-in-nvaf/17569-25222?token=0F0A62B0-3DEA-4143-A812-AE35F7DF154D | Black race is associated with higher rates of atrial fibrillation–related cardiovascular disease compared with White race | Implement telehealth services for anticoagulant education and monitoring | Lower rates of DOACs in Black individuals compared with White individuals | Password Required  | testra+108@mailinator.com | Shivani@123 |        0 | Never   | Strongly Agree | Strongly Agree | Strongly Agree | Strongly Agree | Strongly Agree | Strongly Agree | Strongly Agree | Strongly Agree | Strongly Agree | Strongly Agree |      123 | Yes      | NA       | I do plan to implement changes in my practice based on the information presented | test     | Very committed |       456 | Yes       | test      | Yes       | Competence | Lack of evidence-based guidelines | test      | test      | test      |       .50 |
